### ISSUE TITLE
Versionando pasta da IDE

### ISSUE THREAD

**Issue by maviniciuus** [SDiegoS/Cangaceiro_JavaScript#1]
A pasta `.idea ` criado pelos programas da jetbrains ta versionando, isso causa problemas por causa de alguns paths absolutos com o username, e causa comportamento inesperado quando outra pessoa clona.

Adicionar na raiz um arquivo .gitignore com o conteúdo:
```
# IDE
.idea/
.vscode/
```

depois pode rodar:
`git rm -rf .idea/`

...e reiniciar a IDE!

**Comment by maviniciuus** [comment]
quando resolver esse problema, faz o commit com a hashtag `#1`, assim vai vincular o commit com essa ISSUE que eu criei!

**Comment by SDiegoS** [comment]
Feito
